"""observing pools serenity monitoring tables

Revision ID: 58e25bfcb251
Revises: d5e78f9a1b2c
Create Date: 2026-06-16 09:14:14.607622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e25bfcb251'
down_revision: Union[str, None] = 'd5e78f9a1b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_securities_id'), 'candidate_securities', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_securities_ticker'), 'candidate_securities', ['ticker'], unique=True)
    op.create_table('innovation_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innovation_platforms_id'), 'innovation_platforms', ['id'], unique=False)
    op.create_index(op.f('ix_innovation_platforms_key'), 'innovation_platforms', ['key'], unique=True)
    op.create_table('monitor_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('platform_keys', sa.JSON(), nullable=True),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=True),
    sa.Column('selected_analysts', sa.JSON(), nullable=True),
    sa.Column('lookback_window', sa.String(length=32), nullable=True),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_configs_id'), 'monitor_configs', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_configs_name'), 'monitor_configs', ['name'], unique=True)
    op.create_table('pool_refresh_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=True),
    sa.Column('universe_source', sa.String(length=255), nullable=True),
    sa.Column('universe_version', sa.String(length=64), nullable=True),
    sa.Column('composite_formula_version', sa.String(length=32), nullable=True),
    sa.Column('platform_keys', sa.JSON(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('fetch_errors', sa.JSON(), nullable=True),
    sa.Column('rejected', sa.JSON(), nullable=True),
    sa.Column('token_cost', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_refresh_runs_id'), 'pool_refresh_runs', ['id'], unique=False)
    op.create_table('serenity_research_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('platform_key', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=False),
    sa.Column('chain_layer', sa.String(length=120), nullable=True),
    sa.Column('bottleneck_hypothesis', sa.Text(), nullable=True),
    sa.Column('scorecard', sa.JSON(), nullable=True),
    sa.Column('evidence_grade', sa.String(length=2), nullable=True),
    sa.Column('serenity_score', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.String(length=16), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('downgrade_triggers', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serenity_research_records_id'), 'serenity_research_records', ['id'], unique=False)
    op.create_index(op.f('ix_serenity_research_records_platform_key'), 'serenity_research_records', ['platform_key'], unique=False)
    op.create_index(op.f('ix_serenity_research_records_ticker'), 'serenity_research_records', ['ticker'], unique=False)
    op.create_table('evidence_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('substantiated', sa.Boolean(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('claim_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['serenity_research_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_references_id'), 'evidence_references', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_references_record_id'), 'evidence_references', ['record_id'], unique=False)
    op.create_table('observation_pool_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('platform_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('platform_fit_score', sa.Float(), nullable=True),
    sa.Column('value_investor_score', sa.Float(), nullable=True),
    sa.Column('innovation_growth_score', sa.Float(), nullable=True),
    sa.Column('serenity_bottleneck_score', sa.Float(), nullable=True),
    sa.Column('risk_adjusted_momentum_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('composite_formula_version', sa.String(length=32), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('last_refresh_run_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['last_refresh_run_id'], ['pool_refresh_runs.id'], ),
    sa.ForeignKeyConstraint(['platform_key'], ['innovation_platforms.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'platform_key', name='uq_pool_ticker_platform')
    )
    op.create_index(op.f('ix_observation_pool_entries_id'), 'observation_pool_entries', ['id'], unique=False)
    op.create_index(op.f('ix_observation_pool_entries_last_refresh_run_id'), 'observation_pool_entries', ['last_refresh_run_id'], unique=False)
    op.create_index(op.f('ix_observation_pool_entries_platform_key'), 'observation_pool_entries', ['platform_key'], unique=False)
    op.create_index(op.f('ix_observation_pool_entries_rank'), 'observation_pool_entries', ['rank'], unique=False)
    op.create_index(op.f('ix_observation_pool_entries_ticker'), 'observation_pool_entries', ['ticker'], unique=False)
    op.create_table('opportunity_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('time_horizon', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('agent_signals', sa.JSON(), nullable=True),
    sa.Column('serenity_context', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('next_checks', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitor_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_reports_id'), 'opportunity_reports', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_reports_monitor_id'), 'opportunity_reports', ['monitor_id'], unique=False)
    op.create_index(op.f('ix_opportunity_reports_ticker'), 'opportunity_reports', ['ticker'], unique=False)
    # NOTE: autogenerate also surfaced pre-existing backend model↔migration drift
    # (api_keys unique index, hedge_fund_flow_run_cycles indexes, FK constraints).
    # Those are unrelated to this feature and intentionally NOT applied here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_reports_ticker'), table_name='opportunity_reports')
    op.drop_index(op.f('ix_opportunity_reports_monitor_id'), table_name='opportunity_reports')
    op.drop_index(op.f('ix_opportunity_reports_id'), table_name='opportunity_reports')
    op.drop_table('opportunity_reports')
    op.drop_index(op.f('ix_observation_pool_entries_ticker'), table_name='observation_pool_entries')
    op.drop_index(op.f('ix_observation_pool_entries_rank'), table_name='observation_pool_entries')
    op.drop_index(op.f('ix_observation_pool_entries_platform_key'), table_name='observation_pool_entries')
    op.drop_index(op.f('ix_observation_pool_entries_last_refresh_run_id'), table_name='observation_pool_entries')
    op.drop_index(op.f('ix_observation_pool_entries_id'), table_name='observation_pool_entries')
    op.drop_table('observation_pool_entries')
    op.drop_index(op.f('ix_evidence_references_record_id'), table_name='evidence_references')
    op.drop_index(op.f('ix_evidence_references_id'), table_name='evidence_references')
    op.drop_table('evidence_references')
    op.drop_index(op.f('ix_serenity_research_records_ticker'), table_name='serenity_research_records')
    op.drop_index(op.f('ix_serenity_research_records_platform_key'), table_name='serenity_research_records')
    op.drop_index(op.f('ix_serenity_research_records_id'), table_name='serenity_research_records')
    op.drop_table('serenity_research_records')
    op.drop_index(op.f('ix_pool_refresh_runs_id'), table_name='pool_refresh_runs')
    op.drop_table('pool_refresh_runs')
    op.drop_index(op.f('ix_monitor_configs_name'), table_name='monitor_configs')
    op.drop_index(op.f('ix_monitor_configs_id'), table_name='monitor_configs')
    op.drop_table('monitor_configs')
    op.drop_index(op.f('ix_innovation_platforms_key'), table_name='innovation_platforms')
    op.drop_index(op.f('ix_innovation_platforms_id'), table_name='innovation_platforms')
    op.drop_table('innovation_platforms')
    op.drop_index(op.f('ix_candidate_securities_ticker'), table_name='candidate_securities')
    op.drop_index(op.f('ix_candidate_securities_id'), table_name='candidate_securities')
    op.drop_table('candidate_securities')
    # ### end Alembic commands ###
